# Generated by Django 4.0.3 on 2022-04-26 00:20

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('fname', models.CharField(blank=True, max_length=100, null=True)),
                ('lname', models.CharField(blank=True, max_length=100, null=True)),
                ('street1', models.CharField(blank=True, max_length=200, null=True)),
                ('street2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=5, null=True)),
                ('area1', models.CharField(blank=True, max_length=3, null=True)),
                ('central1', models.CharField(blank=True, max_length=3, null=True)),
                ('line1', models.CharField(blank=True, max_length=4, null=True)),
                ('area2', models.CharField(blank=True, max_length=3, null=True)),
                ('central2', models.CharField(blank=True, max_length=3, null=True)),
                ('line2', models.CharField(blank=True, max_length=4, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('preference', models.CharField(blank=True, choices=[('call', 'Call'), ('text', 'Text'), ('email', 'Email')], default='call', max_length=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lname'],
            },
        ),
    ]
