# Generated by Django 4.2.6 on 2023-11-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_bill_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
