# Generated by Django 4.2.7 on 2023-11-04 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_alter_service_slug'),
        ('billing', '0004_bill_ispaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service'),
        ),
    ]
