# Generated by Django 4.2.7 on 2023-11-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_bill_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='mname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
