# Generated by Django 4.2.7 on 2024-03-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_bill_mname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
