# Generated by Django 4.2.7 on 2024-03-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_bill_final_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='taxed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
