# Generated by Django 4.0.3 on 2022-03-31 18:55

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('pay', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('rate', models.CharField(choices=[('hour', 'Per Hour'), ('salary', 'Salary'), ('flat', 'Flat'), ('interview', 'Discussed at Interview')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('street1', models.CharField(max_length=200)),
                ('street2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=5)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('secondPhoneNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('preference', models.CharField(blank=True, choices=[('call', 'Call'), ('text', 'Text'), ('email', 'Email')], default='call', max_length=5, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
                ('available_start', models.DateField()),
                ('available_end', models.DateField(blank=True, null=True)),
                ('experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=7)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('jobs', models.ManyToManyField(to='careers.job')),
            ],
        ),
    ]
