# Generated by Django 4.0.3 on 2022-04-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_alter_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', max_length=7),
        ),
    ]
