# Generated by Django 4.0.3 on 2022-04-09 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_alter_application_phonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='jobs',
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='careers.job'),
        ),
    ]
