# Generated by Django 4.0.3 on 2022-04-20 23:47

import careers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0007_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
    ]
