# Generated by Django 4.0.3 on 2022-06-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0009_remove_application_area1_remove_application_area2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='home_num',
            new_name='phone1',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='mobile_num',
            new_name='phone2',
        ),
    ]
