# Generated by Django 4.0.3 on 2022-06-07 19:30

import careers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0010_rename_home_num_application_phone1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='phone1',
            new_name='home',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='phone2',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='application',
            name='work',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
