# Generated by Django 4.0.3 on 2022-06-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0012_alter_application_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='preference',
            field=models.CharField(choices=[('mobile', 'Call Mobile'), ('home', 'Call Home'), ('work', 'Call Home'), ('text', 'Text'), ('email', 'Email')], default='mobile', max_length=11),
        ),
    ]
