# Generated by Django 4.0.3 on 2022-06-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0014_rename_available_end_application_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='end',
        ),
        migrations.AddField(
            model_name='application',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
