# Generated by Django 4.0.3 on 2022-06-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0015_remove_application_end_application_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='truck_owned',
            field=models.BooleanField(default=False),
        ),
    ]
