# Generated by Django 4.0.3 on 2022-06-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0016_application_truck_owned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='truck_owned',
            new_name='has_pov',
        ),
    ]
