# Generated by Django 4.0.3 on 2022-06-09 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0017_rename_truck_owned_application_has_pov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='has_pov',
        ),
    ]
