# Generated by Django 4.0.3 on 2022-08-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0018_remove_application_has_pov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='rate',
            field=models.CharField(choices=[('hour', 'Per Hour'), ('salary', 'Salary'), ('flat', 'Flat'), ('discuss', 'Discussed at Interview'), ('none', 'None posted')], max_length=20),
        ),
    ]
