# Generated by Django 4.0.3 on 2022-09-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0019_alter_job_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='home',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='work',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='job',
            name='rate',
            field=models.CharField(choices=[('hour', 'Per Hour'), ('salary', 'Salary'), ('flat', 'Flat'), ('interview', 'Discussed at Interview'), ('none', 'None posted')], max_length=20),
        ),
    ]
