# Generated by Django 4.0.3 on 2022-09-04 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0020_alter_application_home_alter_application_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
