# Generated by Django 4.0.3 on 2022-03-24 22:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=5, max_digits=200)),
                ('rate_type', models.CharField(blank=True, choices=[('hr', 'Per Hour'), ('sqft', 'Square Feet'), ('flat', 'Flat Rate')], max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
