# Generated by Django 4.0.3 on 2022-03-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_price_remove_service_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
