# Generated by Django 4.0.3 on 2022-05-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='featured',
            field=models.CharField(choices=[('main', 'Main'), ('secondary', 'Secondary'), ('none', 'None')], default='none', max_length=9),
        ),
    ]
