# Generated by Django 4.0.3 on 2022-09-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='current_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
