# Generated by Django 4.0.3 on 2022-10-08 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_service_current_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='current_image',
        ),
    ]
