# Generated by Django 4.0.3 on 2023-02-04 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_alter_category_options_portfolio_comparison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='name',
        ),
    ]
