# Generated by Django 4.0.3 on 2023-02-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_remove_portfolio_description_remove_portfolio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='unamed', max_length=100),
        ),
    ]
