# Generated by Django 4.2.7 on 2023-11-11 21:31

from django.db import migrations


def migrate_phone_numbers(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    for profile in Profile.objects.all():
        profile.phone_number1 = f"{profile.area1}-{profile.central1}-{profile.line1}"
        profile.phone_number2 = f"{profile.area2}-{profile.central2}-{profile.line2}"
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.RunPython(migrate_phone_numbers),
    ]
