# Generated by Django 4.2.7 on 2023-11-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20231111_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
