# Generated by Django 4.2.7 on 2023-11-11 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_phone_number1_profile_home_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='area1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='area2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='central1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='central2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='line2',
        ),
    ]
