# Generated by Django 4.2.7 on 2023-11-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_mname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preference',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('call', 'Call'), ('text', 'Text'), ('email', 'Email')], default='call', max_length=5, null=True),
        ),
    ]
