# Generated by Django 4.2.7 on 2023-11-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preference',
            field=models.CharField(blank=True, choices=[('', 'None'), ('home', 'Home'), ('cell', 'Cell'), ('work', 'Work'), ('text', 'Text'), ('email', 'Email')], default='home', max_length=5, null=True),
        ),
    ]
