# Generated by Django 4.2.7 on 2023-11-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preference',
            field=models.CharField(blank=True, choices=[('', 'None'), ('home', 'Home'), ('mobile', 'Mobile'), ('work', 'Work'), ('text', 'Text'), ('email', 'Email')], default='home', max_length=6, null=True),
        ),
    ]
